M48
; DRILL file {KiCad 9.0.2} date 2025-05-28T02:09:20-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-28T02:09:20-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X119.0Y-62.5
X121.0Y-55.0
T2
X107.637Y-55.45
X107.637Y-57.99
X107.637Y-60.53
M30
